CREATE TABLE `financial_release_audits` (
	`id` int AUTO_INCREMENT NOT NULL,
	`manifestId` int NOT NULL,
	`familyId` int,
	`action` varchar(100) NOT NULL,
	`outcome` enum('prepared','updated','blocked','exported') NOT NULL,
	`details` json,
	`actorId` int NOT NULL,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `financial_release_audits_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `financial_release_families` (
	`id` int AUTO_INCREMENT NOT NULL,
	`manifestId` int NOT NULL,
	`familyKey` varchar(96) NOT NULL,
	`workflowType` varchar(80) NOT NULL,
	`displayName` varchar(255) NOT NULL,
	`branch` varchar(160) NOT NULL,
	`releaseStatus` enum('included','held','excluded') NOT NULL DEFAULT 'excluded',
	`statusReason` text NOT NULL,
	`expectedReferencePattern` varchar(255) NOT NULL,
	`partyAndAccountRules` json NOT NULL,
	`calculationRules` json NOT NULL,
	`draftOnlyRestriction` text NOT NULL,
	`firstExpectedTrigger` varchar(500) NOT NULL,
	`apEndpointIdentifier` varchar(500) NOT NULL,
	`apAuthentication` varchar(500) NOT NULL,
	`apScheduleDefinition` varchar(500),
	`shadowTestId` int,
	`candidateRosterEntryId` int,
	`sourceRecordNumber` varchar(128),
	`sourcePreflightAt` timestamp,
	`xeroPreflight` json,
	`currentDocumentSummary` json,
	`legacyWriterIdentifier` varchar(500),
	`legacyWriterOwner` varchar(255),
	`legacyDisableAction` text,
	`conditionPayloadContract` text NOT NULL,
	`rollbackPlan` text NOT NULL,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `financial_release_families_id` PRIMARY KEY(`id`),
	CONSTRAINT `financial_release_family_unique` UNIQUE(`manifestId`,`familyKey`)
);
--> statement-breakpoint
CREATE TABLE `financial_release_manifests` (
	`id` int AUTO_INCREMENT NOT NULL,
	`releaseId` varchar(96) NOT NULL,
	`status` enum('preparation','awaiting_approval','approved','superseded') NOT NULL DEFAULT 'preparation',
	`implementationVersion` varchar(128) NOT NULL,
	`frozenRuleVersion` varchar(128) NOT NULL,
	`frozenRules` json NOT NULL,
	`xeroReadiness` json NOT NULL,
	`vtigerReadiness` json NOT NULL,
	`maintenanceWindow` varchar(255),
	`releaseOwner` varchar(255),
	`currentDocumentManifest` json NOT NULL,
	`includedFamilyCount` int NOT NULL DEFAULT 0,
	`heldFamilyCount` int NOT NULL DEFAULT 0,
	`excludedFamilyCount` int NOT NULL DEFAULT 0,
	`preparedBy` int NOT NULL,
	`preparedAt` timestamp NOT NULL DEFAULT (now()),
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `financial_release_manifests_id` PRIMARY KEY(`id`),
	CONSTRAINT `financial_release_manifest_release_unique` UNIQUE(`releaseId`)
);
