CREATE TABLE `financial_writer_executions` (
	`id` int AUTO_INCREMENT NOT NULL,
	`executionKey` varchar(128) NOT NULL,
	`workflowRunId` int,
	`documentIntentId` int,
	`releaseManifestId` int,
	`releaseFamilyId` int,
	`cutoverPackId` int,
	`workflowType` varchar(80) NOT NULL,
	`documentFamily` enum('purchase_order','customer_invoice') NOT NULL,
	`proposedAction` enum('create_draft','update_draft') NOT NULL,
	`proposedDocumentNumber` varchar(128) NOT NULL,
	`targetXeroDocumentId` varchar(128),
	`endpoint` varchar(500) NOT NULL,
	`method` enum('POST','PUT') NOT NULL,
	`idempotencyKey` varchar(128) NOT NULL,
	`payloadFingerprint` varchar(128) NOT NULL,
	`status` enum('prepared','blocked','submitted','succeeded','failed','reconciliation_required') NOT NULL DEFAULT 'prepared',
	`approvalReference` varchar(255),
	`safePayloadSummary` json,
	`xeroDocumentId` varchar(128),
	`xeroDocumentStatus` varchar(64),
	`xeroResponseSummary` json,
	`errorMessage` text,
	`preparedBy` int,
	`submittedAt` timestamp,
	`completedAt` timestamp,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `financial_writer_executions_id` PRIMARY KEY(`id`),
	CONSTRAINT `financial_writer_execution_key_unique` UNIQUE(`executionKey`),
	CONSTRAINT `financial_writer_execution_idempotency_unique` UNIQUE(`idempotencyKey`)
);
