CREATE TABLE `financial_initial_storage_events` (
	`id` int AUTO_INCREMENT NOT NULL,
	`dealId` varchar(128) NOT NULL,
	`dealNumber` varchar(64) NOT NULL,
	`location` enum('origin','destination') NOT NULL,
	`periodStart` varchar(10) NOT NULL,
	`periodEnd` varchar(10) NOT NULL,
	`suffix` varchar(1) NOT NULL,
	`sourceHash` varchar(64) NOT NULL,
	`containerNumber` varchar(128) NOT NULL,
	`containerType` varchar(80) NOT NULL,
	`status` enum('held','reserved','partial','drafts_created','writeback_pending','failed') NOT NULL DEFAULT 'held',
	`pilotApprovalKey` varchar(96),
	`approvedDocumentsHash` varchar(64),
	`approvedPreflightHash` varchar(64),
	`approvalExpiresAt` timestamp,
	`approvedBy` int,
	`legacyHandoffConfirmedAt` timestamp,
	`documentResults` json,
	`errorMessage` text,
	`retryCount` int NOT NULL DEFAULT 0,
	`receivedAt` timestamp NOT NULL DEFAULT (now()),
	`completedAt` timestamp,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `financial_initial_storage_events_id` PRIMARY KEY(`id`),
	CONSTRAINT `financial_initial_storage_event_unique` UNIQUE(`dealId`,`location`,`periodStart`),
	CONSTRAINT `financial_initial_storage_suffix_unique` UNIQUE(`dealId`,`suffix`)
);
