import { AlertTriangle, CalendarDays, CheckCircle2, LockKeyhole, Warehouse, Webhook } from "lucide-react";
import { Badge } from "@/components/ui/badge";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { FinancialStorageDrafts } from "@/components/FinancialStorageDrafts";
import { StorageLivePreview } from "@/components/StorageLivePreview";
import { StorageFinalPreview } from "@/components/StorageFinalPreview";
import { trpc } from "@/lib/trpc";

export default function StorageAutomation() {
  const receiver = trpc.financialOperations.initialStorageReadiness.useQuery();
  const release = trpc.financialOperations.storageLifecycleReadiness.useQuery();
  const status = release.data;
  const live = status?.automaticWriterEnabled && status.policy.enabled;
  return <div className="mx-auto max-w-6xl space-y-5 pb-12">
    <header className="flex flex-wrap items-start justify-between gap-3"><div><h1 className="flex items-center gap-2 text-2xl font-semibold"><Warehouse className="h-6 w-6" />VTiger → Xero Storage</h1><p className="mt-2 text-sm text-muted-foreground">Loaded-container storage only: initial Drafts, monthly billing and finalisation. No payment or authorisation actions.</p></div><Badge variant="outline">{live ? "Release armed — delivery must be verified" : "Built — live cutover disabled"}</Badge></header>
    <div className="grid gap-3 md:grid-cols-3">
      <Card><CardContent className="p-4"><p className="flex items-center gap-2 font-medium"><Webhook className="h-4 w-4" />Initial storage</p><p className="mt-2 text-sm">Customer invoice + once-only JD transport PO + GD storage PO.</p><p className="mt-2 break-all font-mono text-xs text-muted-foreground">/api/webhooks/vtiger/deal-storage</p><Badge className="mt-3" variant="outline">{receiver.data?.authenticationConfigured ? "Private header configured" : "Checking / header missing"}</Badge></CardContent></Card>
      <Card><CardContent className="p-4"><p className="flex items-center gap-2 font-medium"><CalendarDays className="h-4 w-4" />Monthly storage</p><p className="mt-2 text-sm">Next due period only, first Sydney calendar day. Customer invoice + GD PO; never another JD PO.</p><p className="mt-2 break-all font-mono text-xs text-muted-foreground">{status?.recurringRoute ?? "/api/scheduled/financial-writer/recurring_storage"}</p><Badge className="mt-3" variant="outline">Implemented — schedule activation separate</Badge></CardContent></Card>
      <Card><CardContent className="p-4"><p className="flex items-center gap-2 font-medium"><CheckCircle2 className="h-4 w-4" />Finalise storage</p><p className="mt-2 text-sm">Date Out/delivery caps the last billed period. Updates only exact Draft invoice/GD IDs and stops recurrence.</p><p className="mt-2 break-all font-mono text-xs text-muted-foreground">{status?.finalisationRoute ?? "/api/webhooks/vtiger/deal-storage-finalise"}</p><Badge className="mt-3" variant="outline">Implemented — existing non-Drafts held</Badge></CardContent></Card>
    </div>
    {(receiver.error || release.error) && <p role="alert" className="text-sm text-red-700">Storage readiness could not be loaded; do not infer live status.</p>}
    <Card><CardHeader><CardTitle className="flex items-center gap-2 text-base"><LockKeyhole className="h-4 w-4" />Storage-only release</CardTitle></CardHeader><CardContent className="space-y-2 text-sm"><p>Once separately approved and enabled, qualifying events use one standing storage policy instead of a manual approval per Deal. Current policy: <strong>{status?.policy.enabled ? "enabled" : "disabled"}</strong>; deployment gate: <strong>{status?.automaticWriterEnabled ? "armed" : "off"}</strong>.</p><p className="text-muted-foreground">Operations handoffs: initial {status?.policy.handoffs.activation ? "confirmed" : "not confirmed"} · monthly {status?.policy.handoffs.recurring ? "confirmed" : "not confirmed"} · finalisation {status?.policy.handoffs.finalisation ? "confirmed" : "not confirmed"}. Existing documents are not automatically imported or duplicated.</p><details className="pt-1 text-xs"><summary className="cursor-pointer font-medium">Webhook contract</summary><p className="mt-2">Header: <code>X-Financial-Webhook-Secret</code> (secret never displayed).</p><pre className="mt-2 overflow-auto rounded-md bg-muted p-3">{JSON.stringify({ record_id: "5x123456", event: "deal.storage-stage-changed" }, null, 2)}</pre><pre className="mt-2 overflow-auto rounded-md bg-muted p-3">{JSON.stringify({ record_id: "5x123456", event: "deal.storage-finalised", storageLocation: "origin" }, null, 2)}</pre></details></CardContent></Card>
    <FinancialStorageDrafts />
    <details className="rounded-lg border p-4"><summary className="cursor-pointer text-sm font-medium">Reference checks — no Xero writes</summary><div className="mt-4 space-y-4"><StorageLivePreview /><StorageFinalPreview /></div></details>
    <div className="flex gap-2 rounded-lg border border-amber-200 bg-amber-50 p-4 text-sm text-amber-900"><AlertTriangle className="h-4 w-4 shrink-0" /><p><strong>Next: publish, then confirm the storage-only cutover.</strong> Pause/drain only the matching Operations initial/finalisation writers and monthly job, configure VTiger delivery to AP, and enable the approved storage policy/schedule. None of those external actions is performed by this page. Legacy history, changed final dates and uncertain writes remain held for reconciliation.</p></div>
  </div>;
}
